Add Moogle 1.0 support to VSCode extension
leanprover/vscode-lean4 pull request #528
Opened 2024-10-01 05:32 UTC by jesse-michael-han

2024-10-07 08:25 UTC, mhuisi requested changes

2024-10-07 08:25 UTC, mhuisi commented on vscode-lean4/package.json
> +                    "group": "4_search@2"
```suggestion
                    "group": "4_search@1"
```

2024-10-07 08:25 UTC, mhuisi commented on vscode-lean4/moogleview/static/index.css
> +}
(Question still pending)

2024-10-13 21:39 UTC, pranavnt commented
Just removed `.code` from the CSS and updated the Loogle group to `4_search@1` — thank you, and sorry about the delay!

2024-10-14 10:53 UTC, merged